# Number of days of inactivity before an issue becomes stale
daysUntilStale: 21
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 0
# Only issues or pull requests with all of these labels are check if stale. Defaults to `[]` (disabled)
onlyLabels: ["waiting for reply"]
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: "no response"
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed and marked as "no response" because it has not had
  recent activity. Feel free to reply to get it reopened.
