# TEMPORARILY DEACTIVATED DUE TO DIFFICULTIES CONFIGURING PROPERLY (2019/10/17)

# daysUntilStale: 21
# daysUntilClose: 7
# onlyLabels:
#   - "waiting for reply"
# exemptLabels:
#   - pinned
#   - security
# staleLabel: "no response"
# closeComment: >
#   This issue has been automatically closed because it has not had any
#   recent activity and was marked with "no response". Feel free to reply to get it reopened.
